### ISSUE TITLE
Clicking links in desktop build doesn't open the browser

### ISSUE THREAD

**Issue by jrynkiew** [pthom/imgui_manual#8]
Hi Pascal,

![Screenshot from 2022-03-19 09-29-16](https://user-images.githubusercontent.com/63042547/159113855-03152a74-6e31-46e7-9a3c-01a6540b332f.png)

When I build the imgui_manual using desktop mode (on Linux with X11, SDL2, SDL2_Image) everything works great, but clicking links does not open a new browser window. Can this be fixed? Have you investigated this issue before?

**Comment by pthom** [comment]
Hello,

I did not implement this on desktop mode for linux (since imgui_manual is mainly intended to be used on emscripten).
However, changing this should be easy:

Look at [HyperlinkHelper.cpp](https://github.com/pthom/imgui_manual/blob/master/src/imgui_utilities/HyperlinkHelper.cpp)

Something around this (not tested) should work (if `xdg-open` is installed)
````cpp

void OpenUrl(const std::string &url)
{
...
...
...
#elif defined(TARGET_OS_MAC)
        std::string cmd = std::string("open ") + url.c_str();
        system(cmd.c_str());
#elif defined(__linux__)
    std::string cmd = std::string("xdg-open ") + url;
    system(cmd.c_str()); 
#endif
````

**Comment by jrynkiew** [comment]
Wow, thank You! It worked like a charm straight away!. You're the boss!
